# Generated by Django 5.1.4 on 2024-12-31 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='members',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
