# Generated by Django 5.1.4 on 2024-12-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trello', '0002_remove_comentario_autor_remove_tablero_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='comentario',
        ),
    ]
