# Generated by Django 5.1.4 on 2024-12-31 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trello', '0003_remove_tarea_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='tarea',
        ),
        migrations.AddField(
            model_name='tarea',
            name='comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Trello.comentario'),
            preserve_default=False,
        ),
    ]
