# Generated by Django 5.1.4 on 2024-12-31 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trello', '0005_remove_tarea_comentario_comentario_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='lista',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tablero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Trello.tablero'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
    ]
